model_list: []
litellm_settings:
  drop_params: true
  set_verbose: true
general_settings:
  master_key: sk-1234
  database_url: postgresql://postgres:postgres@postgres:5432/litellm
router_settings:
  routing_strategy: least-busy
  num_retries: 3
  timeout: 600
environment_variables:
  AZURE_AD_TENANT_ID: 76022147-8d47-4942-bcee-e2ae5133aaa2
  AZURE_AD_CLIENT_ID: 47eeac3e-223d-4505-86b0-f1fda8382aad
  AZURE_AD_CLIENT_SECRET: 1jL8Q~3etoUpWcJH.jaLBfoJQyjJ5hcEvPvXga7O
