model_list:
- model_name: qwen3:0.6b
  litellm_params:
    model: ollama/qwen3:0.6b
    api_base: http://ollama:11434
litellm_settings:
  drop_params: true
  set_verbose: true
router_settings:
  routing_strategy: least-busy
  num_retries: 3
  timeout: 600
