name: CI - Build AppHost

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build and Publish (matrix)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rid: [linux-x64, win-x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build solution (or all projects if no .sln)
        shell: bash
        run: |
          set -euo pipefail
          if ls *.sln 1> /dev/null 2>&1; then
            SOLUTION=$(ls -1 *.sln | head -n 1)
            echo "Building solution: $SOLUTION"
            dotnet restore "$SOLUTION"
            dotnet build "$SOLUTION" -c Release --no-restore
          else
            echo "No .sln found; building all projects"
            shopt -u dotglob
            shopt -s globstar nullglob
            projects=(**/*.csproj)
            if [ ${#projects[@]} -eq 0 ]; then
              echo "No .csproj files found" >&2
              exit 1
            fi
            echo "Restoring ${#projects[@]} projects"
            for p in "${projects[@]}"; do
              dotnet restore "$p"
            done
            echo "Building ${#projects[@]} projects"
            for p in "${projects[@]}"; do
              dotnet build "$p" -c Release --no-restore
            done
          fi

      - name: Publish ${{ matrix.rid }} (self-contained single-file)
        run: |
          dotnet publish WolfPackAI.AppHost/WolfPackAI.AppHost.csproj \
            -c Release \
            -r ${{ matrix.rid }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -p:ContinuousIntegrationBuild=true

      - name: Archive artifact ${{ matrix.rid }}
        shell: bash
        run: |
          PUBLISH_DIR="WolfPackAI.AppHost/bin/Release/net9.0/${{ matrix.rid }}/publish"
          echo "Zipping from $PUBLISH_DIR"
          if [ ! -d "$PUBLISH_DIR" ] || [ -z "$(ls -A "$PUBLISH_DIR")" ]; then
            echo "Publish output missing or empty: $PUBLISH_DIR"
            exit 1
          fi
          cd "$PUBLISH_DIR"
          zip -r "$GITHUB_WORKSPACE/WolfPackAI.AppHost-${{ matrix.rid }}.zip" .

      - name: Upload artifact ${{ matrix.rid }}
        uses: actions/upload-artifact@v4
        with:
          name: WolfPackAI.AppHost-${{ matrix.rid }}
          path: WolfPackAI.AppHost-${{ matrix.rid }}.zip
          if-no-files-found: error
